before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./nullstone
archives:
  - files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: nullstone-io
      name: nullstone
    folder: Formula
    homepage: https://nullstone.io
    description: Launch apps on your cloud in minutes
    license: MIT
    install: |-
      bin.install "nullstone"
scoop:
  bucket:
    owner: nullstone-io
    name: nullstone
  homepage: https://nullstone.io
  description: Launch apps on your cloud in minutes
  license: MIT
snapcrafts:
  - id: nullstone
    name: nullstone
    summary: Launch apps and IaC from one platform
    description: A CLI for the Nullstone platform. Install to automate configuration, delivery, and diagnosis of cloud infrastructure.
    license: MIT
    base: bare
    grade: stable
    confinement: strict
    plugs:
      personal-files:
        write:
          - $HOME/.nullstone/
    apps:
      nullstone:
        command: bin/nullstone
        aliases:
          - ns
        plugs: ["personal-files"]
