before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./nullstone
archives:
  - files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: nullstone-io
      name: nullstone
    folder: Formula
    homepage: https://nullstone.io
    description: Launch apps on your cloud in minutes
    license: MIT
    install: |-
      bin.install "nullstone"
scoop:
  bucket:
    owner: nullstone-io
    name: nullstone
  homepage: https://nullstone.io
  description: Launch apps on your cloud in minutes
  license: MIT
