version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./nullstone
archives:
  - files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: nullstone
    homepage: https://nullstone.io
    description: An internal developer platform running on your cloud
    license: MIT
    repository:
      owner: nullstone-io
      name: nullstone
    directory: Formula
    install: |-
      bin.install "nullstone"
    commit_author:
      name: nullstone-release-bot
      email: dev@nullstone.io

scoops:
  - homepage: https://nullstone.io
    description: An internal developer platform running on your cloud
    license: MIT
    repository:
      owner: nullstone-io
      name: nullstone
    commit_author:
      name: nullstone-release-bot
      email: dev@nullstone.io
