# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nullstone < Formula
  desc "An internal developer platform running on your cloud"
  homepage "https://nullstone.io"
  version "0.0.127"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nullstone-io/nullstone/releases/download/v0.0.127/nullstone_0.0.127_darwin_amd64.tar.gz"
      sha256 "bf0821f7b399f5d0c4bcbdd2c2b509fac72d7f5b4ab151f1cd9248ff932a1f2b"

      def install
        bin.install "nullstone"
      end
    end
    on_arm do
      url "https://github.com/nullstone-io/nullstone/releases/download/v0.0.127/nullstone_0.0.127_darwin_arm64.tar.gz"
      sha256 "a2fd3d5b7d776bb231b11cb6965e8aeefffb9f7ba1417debe28a7141e943cd09"

      def install
        bin.install "nullstone"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nullstone-io/nullstone/releases/download/v0.0.127/nullstone_0.0.127_linux_amd64.tar.gz"
        sha256 "aecb46440b41175b7a9a3bf954ed51889bc9e41ed5cca0d47f932ba3c370ad02"

        def install
          bin.install "nullstone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nullstone-io/nullstone/releases/download/v0.0.127/nullstone_0.0.127_linux_arm64.tar.gz"
        sha256 "365b9467ab5852148e8963048e74f30a8d9b06bc62d722a161cf6b721a5eae96"

        def install
          bin.install "nullstone"
        end
      end
    end
  end
end
