# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nullstone < Formula
  desc "Launch apps on your cloud in minutes"
  homepage "https://nullstone.io"
  version "0.0.34"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nullstone-io/nullstone/releases/download/v0.0.34/nullstone_0.0.34_darwin_amd64.tar.gz"
      sha256 "92e21af2e280eb9e517d9e4ff071f39b2b53438cd3d3bf06fce71a3ddebcba86"

      def install
        bin.install "nullstone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nullstone-io/nullstone/releases/download/v0.0.34/nullstone_0.0.34_darwin_arm64.tar.gz"
      sha256 "53eb99101f60da26c918444e7b7a7feffd52025fd865ad5f0e4b73afc5383d83"

      def install
        bin.install "nullstone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nullstone-io/nullstone/releases/download/v0.0.34/nullstone_0.0.34_linux_amd64.tar.gz"
      sha256 "2bf85497aaa1e80c1f9fd743b65612510c269e42985ef682a1d4a29973ad6a27"

      def install
        bin.install "nullstone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nullstone-io/nullstone/releases/download/v0.0.34/nullstone_0.0.34_linux_arm64.tar.gz"
      sha256 "129c4e9134bee7b1692528be27f1130f724fd8a03ab9340bfea2f425f79c1348"

      def install
        bin.install "nullstone"
      end
    end
  end
end
