name: goreleaser

on:
  push:
    tags:
      - 'v*'



jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Find version
        id: version
        run: echo "CLI_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          CLI_VERSION: ${{ env.MODULE_VERSION }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
